import Head from 'next/head'
import { Footer } from '../Footer/Footer'
import { Header } from '../Header/Header'
export const Layout=({children,title})=>{

return (
<>
<Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
<div className="flex justify-between flex-col h-screen">
<Header/>



{children}

<Footer/>
</div>
</>
        )

}